package com.niwe.erp.invoicing.domain;

public enum EPaymentMethod {

	PAYMENT_METHOD_CASH, PAYMENT_METHOD_CHEQUE, PAYMENT_METHOD_TELECOMS, PAYMENT_METHOD_VISA_CARD,
	PAYMENT_METHOD_CREDIT, PAYMENT_METHOD_BANK_TRANSFER, PAYMENT_METHOD_TRANSFER, PAYMENT_METHOD_MOOV_MONEY,
	PAYMENT_METHOD_AIRTEL_MONEY;

}
